name: Docker Image CI

on:
  push:
    branches: [ "mpc_dev" ]
  pull_request:
    branches: [ "mpc_dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag minorplanetcenter/reboundx
    - name: Push the Docker image
      run: docker push minorplanetcenter/reboundx
